//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.01.25 at 10:41:12 PM GMT
//

package net.wicast.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the net.wicast.config package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("http://xml.wicast.net/xml", "Name");
    private final static QName _Version_QNAME = new QName("http://xml.wicast.net/xml", "Version");
    private final static QName _Description_QNAME = new QName("http://xml.wicast.net/xml", "Description");
    private final static QName _Url_QNAME = new QName("http://xml.wicast.net/xml", "Url");
    private final static QName _Organization_QNAME = new QName("http://xml.wicast.net/xml", "Organization");
    private final static QName _Id_QNAME = new QName("http://xml.wicast.net/xml", "Id");
    private final static QName _Title_QNAME = new QName("http://xml.wicast.net/xml", "Title");
    private final static QName _Encoding_QNAME = new QName("http://xml.wicast.net/xml", "Encoding");
    private final static QName _Class_QNAME = new QName("http://xml.wicast.net/xml", "Class");
    private final static QName _File_QNAME = new QName("http://xml.wicast.net/xml", "File");
    private final static QName _Uri_QNAME = new QName("http://xml.wicast.net/xml", "Uri");
    private final static QName _Port_QNAME = new QName("http://xml.wicast.net/xml", "Port");
    private final static QName _Core_QNAME = new QName("http://xml.wicast.net/xml", "Core");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: net.wicast.config
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }.
     * @return the application
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Channel }.
     * @return the channel
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Class")
    public JAXBElement<String> createClass(String value) {
        return new JAXBElement<>(ObjectFactory._Class_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link Client }.
     * @return the client
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Core")
    public JAXBElement<String> createCore(String value) {
        return new JAXBElement<>(ObjectFactory._Core_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<>(ObjectFactory._Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Encoding")
    public JAXBElement<String> createEncoding(String value) {
        return new JAXBElement<>(ObjectFactory._Encoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "File")
    public JAXBElement<String> createFile(String value) {
        return new JAXBElement<>(ObjectFactory._File_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<>(ObjectFactory._Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link Licence }.
     * @return the licence
     */
    public Licence createLicence() {
        return new Licence();
    }

    /**
     * Create an instance of {@link Licenses }.
     * @return the licenses
     */
    public Licenses createLicenses() {
        return new Licenses();
    }

    /**
     * Create an instance of {@link Message }.
     * @return the message
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(ObjectFactory._Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Organization")
    public JAXBElement<String> createOrganization(String value) {
        return new JAXBElement<>(ObjectFactory._Organization_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< integer>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Port")
    public JAXBElement<Integer> createPort(Integer value) {
        return new JAXBElement<>(ObjectFactory._Port_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link Properties }.
     * @return the properties
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Scheduler }.
     * @return the scheduler
     */
    public Scheduler createScheduler() {
        return new Scheduler();
    }

    /**
     * Create an instance of {@link Server }.
     * @return the server
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link Task }.
     * @return the task
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<>(ObjectFactory._Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link Tool }.
     * @return the tool
     */
    public Tool createTool() {
        return new Tool();
    }

    /**
     * Create an instance of {@link Tools }.
     * @return the tools
     */
    public Tools createTools() {
        return new Tools();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<>(ObjectFactory._Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<>(ObjectFactory._Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String
     * }{@code >}}.
     * @param value the value
     * @return the JAXB element< string>
     */
    @XmlElementDecl(namespace = "http://xml.wicast.net/xml", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<>(ObjectFactory._Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link WebAdmin }.
     * @return the web admin
     */
    public WebAdmin createWebAdmin() {
        return new WebAdmin();
    }

}
