//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.01.25 at 10:41:12 PM GMT
//

package net.wicast.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://xml.wicast.net/xml}Name"/&gt;
 *         &lt;element ref="{http://xml.wicast.net/xml}Class"/&gt;
 *         &lt;element ref="{http://xml.wicast.net/xml}Task"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "nameAndClazzAndTask"
})
@XmlRootElement(name = "Scheduler")
public class Scheduler implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2 {

    @XmlElementRefs({
            @XmlElementRef(
                    name = "Class",
                    namespace = "http://xml.wicast.net/xml",
                    type = JAXBElement.class,
                    required = false),
            @XmlElementRef(name = "Task", namespace = "http://xml.wicast.net/xml", type = Task.class, required = false),
            @XmlElementRef(
                    name = "Name",
                    namespace = "http://xml.wicast.net/xml",
                    type = JAXBElement.class,
                    required = false)
    })
    protected List<Object> nameAndClazzAndTask;

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.ToString2#append(org.jvnet.jaxb2_commons.locator.ObjectLocator, java.lang.StringBuilder, org.jvnet.jaxb2_commons.lang.ToStringStrategy2)
     */
    @Override
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.ToString2#appendFields(org.jvnet.jaxb2_commons.locator.ObjectLocator, java.lang.StringBuilder, org.jvnet.jaxb2_commons.lang.ToStringStrategy2)
     */
    @Override
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            List<Object> theNameAndClazzAndTask;
            theNameAndClazzAndTask = nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty()
                    ? getNameAndClazzAndTask() : null;
            strategy.appendField(locator,
                    this,
                    "nameAndClazzAndTask",
                    buffer,
                    theNameAndClazzAndTask,
                    nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty());
        }
        return buffer;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#clone()
     */
    @Override
    public Object clone() {
        return copyTo(createNewInstance());
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo2#copyTo(java.lang.Object)
     */
    @Override
    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo2#copyTo(org.jvnet.jaxb2_commons.locator.ObjectLocator, java.lang.Object, org.jvnet.jaxb2_commons.lang.CopyStrategy2)
     */
    @Override
    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = target == null ? createNewInstance() : target;
        if (draftCopy instanceof Scheduler) {
            final Scheduler copy = (Scheduler) draftCopy;
            {
                final Boolean nameAndClazzAndTaskShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator,
                        nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty());
                if (nameAndClazzAndTaskShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<Object> sourceNameAndClazzAndTask;
                    sourceNameAndClazzAndTask = nameAndClazzAndTask != null
                            && !nameAndClazzAndTask.isEmpty() ? getNameAndClazzAndTask() : null;
                    @SuppressWarnings("unchecked")
                    final List<Object> copyNameAndClazzAndTask = (List<Object>) strategy.copy(
                            LocatorUtils.property(locator, "nameAndClazzAndTask", sourceNameAndClazzAndTask),
                            sourceNameAndClazzAndTask,
                            nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty());
                    copy.nameAndClazzAndTask = null;
                    if (copyNameAndClazzAndTask != null) {
                        final List<Object> uniqueNameAndClazzAndTaskl = copy.getNameAndClazzAndTask();
                        uniqueNameAndClazzAndTaskl.addAll(copyNameAndClazzAndTask);
                    }
                } else {
                    if (nameAndClazzAndTaskShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nameAndClazzAndTask = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo2#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new Scheduler();
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.Equals2#equals(org.jvnet.jaxb2_commons.locator.ObjectLocator, org.jvnet.jaxb2_commons.locator.ObjectLocator, java.lang.Object, org.jvnet.jaxb2_commons.lang.EqualsStrategy2)
     */
    @Override
    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
            EqualsStrategy2 strategy) {
        if (object == null || this.getClass() != object.getClass()) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Scheduler that = (Scheduler) object;
        {
            List<Object> lhsNameAndClazzAndTask;
            lhsNameAndClazzAndTask = nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty()
                    ? getNameAndClazzAndTask() : null;
            List<Object> rhsNameAndClazzAndTask;
            rhsNameAndClazzAndTask = that.nameAndClazzAndTask != null && !that.nameAndClazzAndTask.isEmpty()
                    ? that.getNameAndClazzAndTask() : null;
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nameAndClazzAndTask", lhsNameAndClazzAndTask),
                    LocatorUtils.property(thatLocator, "nameAndClazzAndTask", rhsNameAndClazzAndTask),
                    lhsNameAndClazzAndTask,
                    rhsNameAndClazzAndTask,
                    nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty(),
                    that.nameAndClazzAndTask != null && !that.nameAndClazzAndTask.isEmpty())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Gets the value of the nameAndClazzAndTask property.
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the
     * nameAndClazzAndTask property.
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getNameAndClazzAndTask().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Task }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * @return the name and clazz and task
     */
    public List<Object> getNameAndClazzAndTask() {
        if (nameAndClazzAndTask == null) {
            nameAndClazzAndTask = new ArrayList<>();
        }
        return nameAndClazzAndTask;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.HashCode2#hashCode(org.jvnet.jaxb2_commons.locator.ObjectLocator, org.jvnet.jaxb2_commons.lang.HashCodeStrategy2)
     */
    @Override
    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            List<Object> theNameAndClazzAndTask;
            theNameAndClazzAndTask = nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty()
                    ? getNameAndClazzAndTask() : null;
            currentHashCode = strategy.hashCode(
                    LocatorUtils.property(locator, "nameAndClazzAndTask", theNameAndClazzAndTask),
                    currentHashCode,
                    theNameAndClazzAndTask,
                    nameAndClazzAndTask != null && !nameAndClazzAndTask.isEmpty());
        }
        return currentHashCode;
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.MergeFrom2#mergeFrom(java.lang.Object, java.lang.Object)
     */
    @Override
    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    /* (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.MergeFrom2#mergeFrom(org.jvnet.jaxb2_commons.locator.ObjectLocator, org.jvnet.jaxb2_commons.locator.ObjectLocator, java.lang.Object, java.lang.Object, org.jvnet.jaxb2_commons.lang.MergeStrategy2)
     */
    @Override
    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right,
            MergeStrategy2 strategy) {
        if (right instanceof Scheduler) {
            final Scheduler target = this;
            final Scheduler leftObject = (Scheduler) left;
            final Scheduler rightObject = (Scheduler) right;
            {
                final Boolean nameAndClazzAndTaskShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator,
                        rightLocator,
                        leftObject.nameAndClazzAndTask != null && !leftObject.nameAndClazzAndTask.isEmpty(),
                        rightObject.nameAndClazzAndTask != null && !rightObject.nameAndClazzAndTask.isEmpty());
                if (nameAndClazzAndTaskShouldBeMergedAndSet == Boolean.TRUE) {
                    List<Object> lhsNameAndClazzAndTask;
                    lhsNameAndClazzAndTask = leftObject.nameAndClazzAndTask != null
                            && !leftObject.nameAndClazzAndTask.isEmpty() ? leftObject.getNameAndClazzAndTask()
                                    : null;
                    List<Object> rhsNameAndClazzAndTask;
                    rhsNameAndClazzAndTask = rightObject.nameAndClazzAndTask != null
                            && !rightObject.nameAndClazzAndTask.isEmpty() ? rightObject.getNameAndClazzAndTask()
                                    : null;
                    final List<Object> mergedNameAndClazzAndTask = (List<Object>) strategy.merge(
                            LocatorUtils.property(leftLocator, "nameAndClazzAndTask", lhsNameAndClazzAndTask),
                            LocatorUtils.property(rightLocator, "nameAndClazzAndTask", rhsNameAndClazzAndTask),
                            lhsNameAndClazzAndTask,
                            rhsNameAndClazzAndTask,
                            leftObject.nameAndClazzAndTask != null && !leftObject.nameAndClazzAndTask.isEmpty(),
                            rightObject.nameAndClazzAndTask != null
                                    && !rightObject.nameAndClazzAndTask.isEmpty());
                    target.nameAndClazzAndTask = null;
                    if (mergedNameAndClazzAndTask != null) {
                        final List<Object> uniqueNameAndClazzAndTaskl = target.getNameAndClazzAndTask();
                        uniqueNameAndClazzAndTaskl.addAll(mergedNameAndClazzAndTask);
                    }
                } else {
                    if (nameAndClazzAndTaskShouldBeMergedAndSet == Boolean.FALSE) {
                        target.nameAndClazzAndTask = null;
                    }
                }
            }
        }
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

}
