
package net.wicast;

import static org.hamcrest.CoreMatchers.notNullValue;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;

public class ChannelTest {

    private static final Logger LOG = LoggerFactory.getLogger(ChannelTest.class);

    @Test
    public void testTypicalUsage() {
        final ChannelInterface channel = new Channel();
        assertNotNull(channel);
        assertEquals(channel, channel.send(new Message()));
        LOG.debug("{}", channel);
    }

    @Test
    public void type() {
        // TODO auto-generated by JUnit Helper.
        assertThat(Channel.class, notNullValue());
    }

    @Test
    public void instantiation() {
        // TODO auto-generated by JUnit Helper.
        final Channel target = new Channel();
        assertThat(target, notNullValue());
        LOG.debug("{}", target);
    }

}
