
package net.wicast;

import static org.hamcrest.CoreMatchers.notNullValue;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;

public class MessageTest {

    private static final Logger LOG = LoggerFactory.getLogger(MessageTest.class);

    @Test
    public void testTypicalUsage() {
        final Message message = new Message();
        assertNotNull(message);
        assertEquals(message, message.send(new Channel()));
        LOG.debug(message.toString());
    }

    @Test
    public void type() {
        // TODO auto-generated by JUnit Helper.
        assertThat(Channel.class, notNullValue());
    }

    @Test
    public void instantiation() {
        // TODO auto-generated by JUnit Helper.
        final Message message = new Message();
        assertThat(message, notNullValue());
        LOG.debug("{}", message);
    }

}
